export const traderCopy = {
  pl: {
    title: "FluxBase TraderBot",
    subtitle: "Analiza rynku, paper trading i automatyczne strategie dla rynku memcoinów.",
    tabs: {
      market: "Analiza rynku",
      paper: "Paper trading",
      copy: "FOMO Copy",
      ai_bots: "Boty OpenAI",
      live: "Automatyczny trading",
      approvals: "Zlecenia do akceptacji",
      history: "Historia transakcji",
      settings: "Ustawienia i ryzyko",
      exchange: "Połączenie z giełdą",
    },
    statuses: {
      watch: "Obserwuj",
      buy: "Kupno",
      hold: "Trzymaj",
      sell: "Sprzedaż",
      rejected: "Odrzucony",
      low: "Niskie",
      medium: "Średnie",
      high: "Wysokie",
      blocked: "Zablokowane",
      disabled: "Wyłączony",
      approval_required: "Wymagana akceptacja",
      automatic: "Automatyczny",
      pending: "Oczekuje",
      approved: "Zatwierdzone",
      expired: "Wygasłe",
      cancelled: "Anulowane",
    },
  },
};
